#!/bin/bash
# ============================================================
#   ██╗  ██╗ █████╗ ██╗     ██╗    ████████╗██╗  ██╗
#   ██║ ██╔╝██╔══██╗██║     ██║    ╚══██╔══╝╚██╗██╔╝
#   █████╔╝ ███████║██║     ██║       ██║    ╚███╔╝
#   ██╔═██╗ ██╔══██║██║     ██║       ██║    ██╔██╗
#   ██║  ██╗██║  ██║███████╗██║       ██║   ██╔╝ ██╗
#   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝       ╚═╝   ╚═╝  ╚═╝
#
#   KALI-TX — Toolkit Pentest Bash
#   Auteur   : kali-tx
#   Usage    : bash kali_pentest.sh
# ============================================================

# --- Couleurs ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
WHITE='\033[1;37m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# --- Vérification root ---
check_root() {
    if [[ $EUID -ne 0 ]]; then
        echo -e "${YELLOW}[!] Certaines fonctions nécessitent les droits root.${RESET}"
        echo -e "${DIM}    Relancer avec sudo pour un accès complet.${RESET}"
        sleep 1
    fi
}

# --- Bannière ---
banner() {
    clear
    echo -e "${RED}"
    echo "  ██╗  ██╗ █████╗ ██╗     ██╗    ████████╗██╗  ██╗"
    echo "  ██║ ██╔╝██╔══██╗██║     ██║    ╚══██╔══╝╚██╗██╔╝"
    echo "  █████╔╝ ███████║██║     ██║       ██║    ╚███╔╝ "
    echo "  ██╔═██╗ ██╔══██║██║     ██║       ██║    ██╔██╗ "
    echo "  ██║  ██╗██║  ██║███████╗██║       ██║   ██╔╝ ██╗"
    echo "  ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝       ╚═╝   ╚═╝  ╚═╝"
    echo -e "${RESET}"
    echo -e "${DIM}  ─────────────────────────────────────────────────────${RESET}"
    echo -e "${WHITE}   Kali Linux Pentest Toolkit  ${DIM}v1.0  |  $(date '+%d/%m/%Y %H:%M')${RESET}"
    echo -e "${DIM}  ─────────────────────────────────────────────────────${RESET}"
    echo ""
    
}
fenettre_principal() {
     
    echo "1. Analyse réseux"
    echo "2.Analyse image "
    echo "3.Automatisation intellignente"
    echo "4.Système défensif"
    echo "5. Pentest"
    read -p "Quelle est votre choix" choix 
    Choix   
}

Choix(){
    if [[Choix == "1"]]; then 
        echo "Que voulez vous dans l'analye réseau?"
        Analyse_réseaux
}
