#!/bin/bash

# Make scripts executable
chmod +x SecondCerveau3D/build_all.sh
chmod +x SecondCerveau3D/integrate_with_agents.sh
chmod +x SecondCerveau3D/QUICK_START.sh

echo "════════════════════════════════════════════════════════════"
echo "  SecondCerveau3D - Structure créée avec succès! ✓"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📁 STRUCTURE COMPLÈTE:"
echo ""
tree -L 2 -I 'node_modules|.git|build' SecondCerveau3D/ 2>/dev/null || find SecondCerveau3D -type f -name "*.c" -o -name "*.h" -o -name "*.cpp" -o -name "*.java" -o -name "*.py" -o -name "*.jsx" -o -name "*.js" -o -name "*.json" -o -name "*.sh" -o -name "*.md" | head -30
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🚀 DÉMARRAGE RAPIDE:"
echo ""
echo "1️⃣  Compilation:"
echo "   cd SecondCerveau3D"
echo "   ./build_all.sh"
echo ""
echo "2️⃣  Intégration:"
echo "   ./integrate_with_agents.sh"
echo ""
echo "3️⃣  Services:"
echo "   Terminal 1 - Backend Java:"
echo "     cd backend-java && mvn spring-boot:run"
echo ""
echo "   Terminal 2 - UI Electron:"
echo "     cd electron-ui && npm install && npm start"
echo ""
echo "4️⃣  Accès:"
echo "   🖥️  Interface: http://localhost:3000"
echo "   🔌 API: http://localhost:8080"
echo "   🌐 WebSocket: ws://localhost:8080/ws"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📚 DOCUMENTATION:"
echo "   • README.md - Vue d'ensemble"
echo "   • ARCHITECTURE.md - Architecture détaillée"
echo "   • QUICK_START.sh - Guide rapide"
echo ""
echo "🔧 COMPOSANTS:"
echo "   ✅ C Scanner - Scanning de fichiers haute performance"
echo "   ✅ C++ Graph - Moteur de visualisation 3D"
echo "   ✅ Java Backend - API REST + Orchestration"
echo "   ✅ Python Analysis - Moteur d'analyse de menaces"
echo "   ✅ C# Bridge - Intégration P/Invoke"
echo "   ✅ Electron UI - Interface 3D interactive"
echo ""
echo "════════════════════════════════════════════════════════════"
